# Generated by Django 2.2.24 on 2021-12-22 07:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkcategory',
            name='parent',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='app.ParentCategory', verbose_name='主食・副食・飲み物'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maincategory',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.ParentCategory', verbose_name='主食・副食・飲み物'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='parent',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='app.ParentCategory', verbose_name='主食・副食・飲み物'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateField(default=datetime.date.today, verbose_name='作成日'),
        ),
    ]
