# Generated by Django 3.1.14 on 2021-12-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211215_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
        migrations.AddField(
            model_name='profile',
            name='day_kacal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='１日の摂取カロリー'),
        ),
    ]
