# Generated by Django 3.1.14 on 2021-12-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211215_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='day_kacal',
            field=models.IntegerField(default=0, null=True, verbose_name='１日の摂取カロリー'),
        ),
    ]
