# Generated by Django 2.2.24 on 2021-12-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211227_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='meals',
            field=models.IntegerField(default=1, null=True, verbose_name='食事回数'),
        ),
    ]
