# Generated by Django 3.1.14 on 2021-12-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211215_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='day_kacal',
            new_name='day_kcal',
        ),
        migrations.AlterField(
            model_name='profile',
            name='target',
            field=models.TextField(max_length=300, verbose_name='目標'),
        ),
    ]
