# Generated by Django 2.2.24 on 2021-12-27 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211227_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 12, 27, 12, 24, 46, 359209), verbose_name='作成時間'),
        ),
    ]
