# Generated by Django 2.2.24 on 2021-12-28 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211227_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='meals',
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 12, 28, 15, 31, 4, 356270), verbose_name='作成時間'),
        ),
    ]
