# Generated by Django 2.2.24 on 2021-12-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211215_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=30, null=True, verbose_name='年齢'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(verbose_name='作成日'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ParentCategory',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
