# Generated by Django 2.2.24 on 2022-01-01 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211228_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuneCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', models.CharField(max_length=100, verbose_name='食事回数')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 1, 1, 13, 33, 31, 394487), verbose_name='作成時間'),
        ),
    ]
