# Generated by Django 2.2.24 on 2021-12-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211216_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentCategorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='親カテゴリー')),
            ],
        ),
    ]
