# Generated by Django 2.2.24 on 2021-12-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_parentcategorys'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkCategorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='飲み物')),
            ],
        ),
        migrations.CreateModel(
            name='MainCategorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='主食')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='副食')),
            ],
        ),
    ]
