# Generated by Django 2.2.24 on 2022-01-01 05:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220101_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.MuneCount', verbose_name='食事回数'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 1, 1, 14, 2, 18, 474513), verbose_name='作成時間'),
        ),
    ]
