# Generated by Django 2.2.24 on 2021-12-16 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_drinkcategorys_maincategorys_subcategorys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrinkCategorys',
            new_name='DrinkCategory',
        ),
        migrations.RenameModel(
            old_name='MainCategorys',
            new_name='MainCategory',
        ),
        migrations.RenameModel(
            old_name='ParentCategorys',
            new_name='ParentCategory',
        ),
        migrations.RenameModel(
            old_name='SubCategorys',
            new_name='SubCategory',
        ),
    ]
