# Generated by Django 3.2.11 on 2022-01-14 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220101_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 1, 14, 11, 34, 47, 338678), verbose_name='作成時間'),
        ),
    ]
