# Generated by Django 3.2.11 on 2022-01-14 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 1, 14, 11, 50, 45, 190240), verbose_name='作成時間'),
        ),
    ]
