# Generated by Django 2.2.24 on 2021-12-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='作成日'),
        ),
    ]
