# Generated by Django 2.2.24 on 2021-12-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20211221_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateField(verbose_name='作成日'),
        ),
    ]
